pipeline
{
    agent any
    
    stages 
    {
        
        stage('Build Application') 
         {
            
            steps
            {
                
                bat 'mvn -f integ-Maven-tutorial2/pom.xml clean package'
                
            }
            post
            {
                success 
                {
                    
                    echo "Archiving the artifacts ......."
                    
                    archiveArtifacts artifacts: '**/*.war'
                }

                
                
            }

            
            
        }
        stage('create tomcat Docker image')
         {
            steps
             {   
          
                bat 'docker build -t tomcatsampleimage:${env.BUILD_ID} .'    
          
              }               
                               
                                   
                         
          }
                          
                                        
          

        
    }

}

   

    
    
    
    

